### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by alerque** [fonts/ufo2otf#6]
Are you interested in reviving this project? I'm interested in a tool that does this but isn't broken. I'm considering whether to work on a new one or whether you might be open to me revamping this one to do what it says on the tin using the current state of dependencies.

**Comment by jonassmedegaard** [comment]
@alerque depending on what exactly you mean by "a tool that does this", you might find [fontmake](https://github.com/googlefonts/fontmake) a suitable alternative.

**Comment by alerque** [comment]
Seeing as how `fontmake` is both faster and more correct, I don't see any point in reviving this. I had an idea a smaller footprint single-purpose tool would be better for some use cases, but since writing this have changed my mind (and indeed headed the opposite direction and written [a tool with a much bigger footprint](https://github.com/theleagueof/fontship) that combines existing tooling such as fontmake and others into a full blown build system).

As far as I'm concerned project should probably be officially deprecated and the repository marked as archived.
